### ISSUE TITLE
Modify for Open Conf

### ISSUE THREAD

**Issue by JayeshVP24** [tcet-opensource/open-conf#1]
# Navbar
- [ ] Change name to OpenConf
- [ ] Change Navbar content to below content
- [ ] remove pro version button
- [ ] rename free download to contact us
## Navbar content
- Home
- About
- Agenda
- Organizers
- FAQs
 
# Hero
- [ ] Add one call to action button
- [ ] Modify background photo

# organziers
- [ ] change here are our heros to organizers
- [ ] Add organizers photos and socials and title (will add this content in diff comment)

# Work with us
- [ ] Comment out work with us section

# FAQs
- [ ] Find an FAQ component online or in material-tailwind and add it here, add dummy content for now

# Footer
- [ ] Change name to OpenConf
- [ ] Change socials
- [ ] Change links
- [ ] change copyright to tcet-opensource

**Comment by JayeshVP24** [comment]
contact us button -> mailto:opensource@tcetmumbai.in

**Comment by shlok-2003** [comment]
@JayeshVP24 Should I close this thread, as merging is done??
